package com.upax.zemytalents.domain.models

/**
 * Original File
 * https://docs.google.com/spreadsheets/d/1gZHRjOPWO0xOv3TeD-WxC5jWmHMWi_bJaxoTnrdveqA/edit?gid=1206861524#gid=1206861524
 */
internal enum class ZEMTCaptionCatalog(val sectionId: Int) {
    CONVERSACIONES_TIP(1),
    FORMADOR_HOME_BIENVENIDA(2),
    FORMADOR_OPCION_CONVERSACIONES(3),
    FORMADOR_OPCION_COLABORADORES(4),
    FORMADOR_TIP_SLIDE2(5),
    FORMADOR_TIP_SLIDE4(6),
    FORMADOR_TIPOS_CONVERSACION_TIP_SLIDE1(7),
    FORMADOR_INICIAR_CONVERSACION_SLIDE1(8),
    FORMADOR_INICIAR_CONVERSACION_SLIDE2(9),
    FORMADOR_INICIAR_CONVERSACION_SLIDE3(10),
    FORMADOR_CONVERSACION_SELECCION(11),
    FORMADOR_CONVERSACION_PASO2(12),
    FORMADOR_CONVERSACION_PASO4(13),
    MIS_TALENTOS_TAB_HISTORIAL_TIP1(14)
}